### ISSUE TITLE
Error message while calling cli50

### ISSUE THREAD

**Issue by kuelshammer** [cs50/cli#66]
C:\tools\Cmder
λ cli50
Using default tag: latest
latest: Pulling from cs50/cli
Digest: sha256:d9bc084486eb3cbe444416625dff1737afa5a187e0199d8395b57ecd5f77d1cb
Status: Image is up to date for cs50/cli:latest
Traceback (most recent call last):
  File "C:\Python37\Scripts\cli50-script.py", line 11, in <module>
    load_entry_point('cli50==3.0.0', 'console_scripts', 'cli50')()
  File "c:\python37\lib\site-packages\cli50\__main__.py", line 172, in main
    child = pexpect.spawn("docker", ["start", "--attach", "--interactive", container], dimensions=(lines, columns),
AttributeError: module 'pexpect' has no attribute 'spawn'

Working on Win10, Docker Desktop, Python 3.7

**Comment by dmalan** [comment]
Thank you for the report, we're working on a solution!

**Comment by dmalan** [comment]
This should now be fixed, @kuelshammer, if you update with, e.g.:

```
sudo pip3 install cli50 --upgrade
```
